import React, { useEffect, useState } from 'react';
import { Bell, CalendarDays, Check, Flame, LockKeyhole, Save, Shield, Sparkles, Target, UserRound } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import API from '../services/api';
import { useAuth } from '../context/authContext.js';
import { useToast } from '../context/ToastContext';
import ElectricCard from '../components/ui/ElectricCard';
import SecuritySettings from '../components/settings/SecuritySettings';
import ConfirmModal from '../components/ui/ConfirmModal';

const browserTimezone = Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC';
const timezones = [...new Set([browserTimezone, 'UTC', 'Asia/Kolkata', 'America/New_York', 'America/Los_Angeles', 'Europe/London', 'Europe/Berlin', 'Asia/Singapore', 'Asia/Tokyo', 'Australia/Sydney'])];
const defaults = {
    timezone: browserTimezone,
    adaptiveTimeEstimation: true, focusSessionMinutes: 45, defaultDailyMinutes: 120, preferredStudyTime: 'evening', defaultDifficulty: 'medium', autoStartFocusTimer: false,
    autoDetectMissed: true, rescueSuggestions: true, rescueThreshold: 60, preserveLowPriority: true,
    notifications: {
        inApp: { taskReminders: true, deadlineAlerts: true, planHealthAlerts: true, rescueSuggestions: true, achievements: true, streaks: true },
        email: { enabled: true, importantDeadlines: true, missedWorkAlerts: true, planAtRisk: true, ordinaryTaskReminders: false, weeklySummary: true, dailySummary: false }
    },
    planning: { sessionLengthMinutes: 45, dailyAvailabilityMinutes: 120, difficulty: 'medium', priority: 'medium', allowBusyDays: true, unavailableDays: [] },
    gamification: { showXP: true, showStreak: true, achievementAnimations: true, completionAnimations: true }
};
const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
const mergeSettings = (value = {}) => ({ ...defaults, ...value, notifications: { inApp: { ...defaults.notifications.inApp, ...value.notifications?.inApp }, email: { ...defaults.notifications.email, ...value.notifications?.email } }, planning: { ...defaults.planning, ...value.planning }, gamification: { ...defaults.gamification, ...value.gamification } });

const Section = ({ icon: Icon, title, subtitle, children }) => <ElectricCard className="space-y-5"><div className="flex items-start gap-3 border-b border-slate-200 pb-4 dark:border-slate-800"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-orange-200 bg-orange-50 text-orange-600 dark:border-orange-500/30 dark:bg-orange-500/10 dark:text-orange-400"><Icon className="h-5 w-5" /></div><div><h3 className="text-lg font-bold text-slate-900 dark:text-slate-100">{title}</h3><p className="text-sm text-slate-600 dark:text-slate-400">{subtitle}</p></div></div><div className="space-y-5">{children}</div></ElectricCard>;
const SelectField = ({ label, description, value, onChange, options }) => <label className="block"><span className="block text-sm font-semibold text-slate-800 dark:text-slate-200">{label}</span>{description && <span className="mt-1 block text-xs text-slate-600 dark:text-slate-400">{description}</span>}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-900 focus:border-orange-500 focus:outline-none focus:ring-2 focus:ring-orange-200 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100 sm:max-w-sm">{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>;
const ToggleRow = ({ label, description, checked, onChange }) => <div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-slate-800 dark:text-slate-200">{label}</p><p className="mt-1 text-xs leading-5 text-slate-600 dark:text-slate-400">{description}</p></div><button type="button" role="switch" aria-label={label} aria-checked={checked} onClick={() => onChange(!checked)} className={`relative mt-0.5 h-6 w-11 shrink-0 rounded-full transition-colors ${checked ? 'bg-orange-500' : 'bg-slate-300 dark:bg-slate-700'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition-transform ${checked ? 'left-6' : 'left-1'}`} /></button></div>;

const SettingsPage = () => {
    const { user } = useAuth();
    const { addToast } = useToast();
    const navigate = useNavigate();
    const [settings, setSettings] = useState(defaults);
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);
    const [confirmDelete, setConfirmDelete] = useState(false);

    useEffect(() => {
        const load = async () => {
            try { const response = await API.get('/auth/settings'); setSettings(mergeSettings(response.data)); }
            catch { addToast('Using default preferences until settings are available.', 'warning'); }
            finally { setLoading(false); }
        };
        load();
    }, []);

    const update = (key, value) => setSettings((current) => ({ ...current, [key]: value }));
    const updateGroup = (group, key, value) => setSettings((current) => ({ ...current, [group]: { ...current[group], [key]: value } }));
    const updateNotification = (channel, key, value) => setSettings((current) => ({ ...current, notifications: { ...current.notifications, [channel]: { ...current.notifications[channel], [key]: value } } }));
    const save = async () => { setSaving(true); try { const response = await API.patch('/auth/settings', settings); setSettings(mergeSettings(response.data)); addToast('Preferences saved successfully.', 'success'); } catch { addToast('Unable to save preferences right now.', 'error'); } finally { setSaving(false); } };
    const reset = () => { setSettings(defaults); addToast('Preferences reset to defaults. Save to keep these changes.', 'info'); };
    const toggleDay = (day) => updateGroup('planning', 'unavailableDays', settings.planning.unavailableDays.includes(day) ? settings.planning.unavailableDays.filter((item) => item !== day) : [...settings.planning.unavailableDays, day]);

    if (loading) return <div className="py-20 text-center text-sm text-slate-600 dark:text-slate-400">Loading preferences...</div>;
    return <div className="space-y-6 pb-12">
        <div><h2 className="text-2xl font-extrabold text-slate-900 dark:text-white">Settings</h2><p className="text-sm text-slate-600 dark:text-slate-400">Shape how Study Streak Rescue plans, motivates, and supports you.</p></div>
        <Section icon={Target} title="Study Preferences" subtitle="Set your default planning preferences."><div className="grid gap-5 sm:grid-cols-2"><SelectField label="Preferred Focus Session" value={settings.focusSessionMinutes} onChange={(value) => update('focusSessionMinutes', Number(value))} options={[[30, '30 minutes'], [45, '45 minutes'], [60, '60 minutes'], [90, '90 minutes']]} /><SelectField label="Default Daily Study Time" value={settings.defaultDailyMinutes} onChange={(value) => update('defaultDailyMinutes', Number(value))} options={[[30, '30 min'], [60, '1 hour'], [90, '1.5 hours'], [120, '2 hours'], [180, '3 hours'], [240, '4 hours'], [0, 'Custom']]} /><SelectField label="Preferred Study Time" value={settings.preferredStudyTime} onChange={(value) => update('preferredStudyTime', value)} options={[["morning", 'Morning'], ["afternoon", 'Afternoon'], ["evening", 'Evening'], ["night", 'Night'], ["none", 'No Preference']]} /><SelectField label="Default Difficulty" value={settings.defaultDifficulty} onChange={(value) => update('defaultDifficulty', value)} options={[["easy", 'Easy'], ["medium", 'Medium'], ["hard", 'Hard']]} /></div><ToggleRow label="Adaptive Time Estimation" description="Use completed focus sessions to improve future estimates. Existing schedules stay unchanged until you rebalance them." checked={settings.adaptiveTimeEstimation} onChange={(value) => update('adaptiveTimeEstimation', value)} /><ToggleRow label="Auto-start Focus Timer" description="Automatically start the timer when opening a focus task." checked={settings.autoStartFocusTimer} onChange={(value) => update('autoStartFocusTimer', value)} /></Section>
        <Section icon={Sparkles} title="Rescue Preferences" subtitle="Control how Study Streak Rescue responds when you fall behind."><ToggleRow label="Auto Detect Missed Tasks" description="Automatically mark unfinished tasks from previous days as missed." checked={settings.autoDetectMissed} onChange={(value) => update('autoDetectMissed', value)} /><ToggleRow label="Rescue Suggestions" description="Show Rescue My Plan recommendations when your Plan Health drops." checked={settings.rescueSuggestions} onChange={(value) => update('rescueSuggestions', value)} /><SelectField label="Rescue Threshold" description="When Plan Health drops below this number, recommend Rescue My Plan." value={settings.rescueThreshold} onChange={(value) => update('rescueThreshold', Number(value))} options={[[70, 'Plan Health below 70%'], [60, 'Plan Health below 60%'], [50, 'Plan Health below 50%']]} /><ToggleRow label="Preserve Low-Priority Tasks" description="When possible, keep low-priority topics instead of deferring them during rescue." checked={settings.preserveLowPriority} onChange={(value) => update('preserveLowPriority', value)} /></Section>
        <Section icon={Bell} title="Notifications" subtitle="Keep routine coaching in the app and reserve email for important alerts.">
            <SelectField label="Your timezone" description="Used for today, tomorrow, deadline, and weekly-summary checks." value={settings.timezone} onChange={(value) => update('timezone', value)} options={timezones.map((zone) => [zone, zone.replaceAll('_', ' ')])} />
            <div><p className="mb-3 text-xs font-bold uppercase tracking-wider text-slate-500">In-app</p><div className="space-y-4">
                <ToggleRow label="Task reminders" description="Today's schedule and task due alerts." checked={settings.notifications.inApp.taskReminders} onChange={(value) => updateNotification('inApp', 'taskReminders', value)} />
                <ToggleRow label="Deadline alerts" description="Important plan and goal deadlines." checked={settings.notifications.inApp.deadlineAlerts} onChange={(value) => updateNotification('inApp', 'deadlineAlerts', value)} />
                <ToggleRow label="Plan health alerts" description="Warnings when Plan Health needs attention." checked={settings.notifications.inApp.planHealthAlerts} onChange={(value) => updateNotification('inApp', 'planHealthAlerts', value)} />
                <ToggleRow label="Rescue suggestions" description="Actionable missed-work and rescue updates." checked={settings.notifications.inApp.rescueSuggestions} onChange={(value) => updateNotification('inApp', 'rescueSuggestions', value)} />
                <ToggleRow label="Achievements" description="Achievement unlocks and rewards." checked={settings.notifications.inApp.achievements} onChange={(value) => updateNotification('inApp', 'achievements', value)} />
                <ToggleRow label="Streak updates" description="Meaningful study-streak updates." checked={settings.notifications.inApp.streaks} onChange={(value) => updateNotification('inApp', 'streaks', value)} />
            </div></div>
            <div className="border-t border-slate-200 pt-5 dark:border-slate-800"><p className="mb-3 text-xs font-bold uppercase tracking-wider text-slate-500">Email</p><div className="space-y-4">
                <ToggleRow label="Email notifications" description="Master switch for study alerts. Required security emails remain enabled." checked={settings.notifications.email.enabled} onChange={(value) => updateNotification('email', 'enabled', value)} />
                <div className={settings.notifications.email.enabled ? 'space-y-4' : 'pointer-events-none space-y-4 opacity-50'}>
                    <ToggleRow label="Important deadlines" description="Major plan or goal deadlines approaching." checked={settings.notifications.email.importantDeadlines} onChange={(value) => updateNotification('email', 'importantDeadlines', value)} />
                    <ToggleRow label="Plan at risk" description="Critical Plan Health and infeasible schedules." checked={settings.notifications.email.planAtRisk} onChange={(value) => updateNotification('email', 'planAtRisk', value)} />
                    <ToggleRow label="Major missed-work alerts" description="Grouped alerts when multiple tasks become overdue." checked={settings.notifications.email.missedWorkAlerts} onChange={(value) => updateNotification('email', 'missedWorkAlerts', value)} />
                    <ToggleRow label="Ordinary task reminders" description="Email about normal task deadlines. Off by default." checked={settings.notifications.email.ordinaryTaskReminders} onChange={(value) => updateNotification('email', 'ordinaryTaskReminders', value)} />
                    <ToggleRow label="Weekly progress summary" description="One weekly progress email." checked={settings.notifications.email.weeklySummary} onChange={(value) => updateNotification('email', 'weeklySummary', value)} />
                    <ToggleRow label="Daily summary" description="One daily digest instead of separate task emails. Off by default." checked={settings.notifications.email.dailySummary} onChange={(value) => updateNotification('email', 'dailySummary', value)} />
                </div>
            </div></div>
        </Section>        <Section icon={CalendarDays} title="Planning Defaults" subtitle="These values will be pre-filled when creating a new plan."><div className="grid gap-5 sm:grid-cols-2"><SelectField label="Default Session Length" value={settings.planning.sessionLengthMinutes} onChange={(value) => updateGroup('planning', 'sessionLengthMinutes', Number(value))} options={[[30, '30 minutes'], [45, '45 minutes'], [60, '60 minutes'], [90, '90 minutes']]} /><SelectField label="Default Daily Availability" value={settings.planning.dailyAvailabilityMinutes} onChange={(value) => updateGroup('planning', 'dailyAvailabilityMinutes', Number(value))} options={[[60, '1 hour'], [90, '1.5 hours'], [120, '2 hours'], [180, '3 hours'], [240, '4 hours']]} /><SelectField label="Preferred Difficulty" value={settings.planning.difficulty} onChange={(value) => updateGroup('planning', 'difficulty', value)} options={[["easy", 'Easy'], ["medium", 'Medium'], ["hard", 'Hard']]} /><SelectField label="Default Priority" value={settings.planning.priority} onChange={(value) => updateGroup('planning', 'priority', value)} options={[["low", 'Low'], ["medium", 'Medium'], ["high", 'High']]} /></div><ToggleRow label="Allow Busy Days" description="Choose common unavailable days to exclude from scheduling by default." checked={settings.planning.allowBusyDays} onChange={(value) => updateGroup('planning', 'allowBusyDays', value)} />{settings.planning.allowBusyDays && <div className="flex flex-wrap gap-2">{days.map((day) => <button key={day} type="button" onClick={() => toggleDay(day)} className={`rounded-xl border px-3 py-2 text-xs font-semibold ${settings.planning.unavailableDays.includes(day) ? 'border-orange-300 bg-orange-50 text-orange-700 dark:border-orange-500/40 dark:bg-orange-500/10 dark:text-orange-300' : 'border-slate-200 bg-white text-slate-600 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-400'}`}>{settings.planning.unavailableDays.includes(day) && <Check className="mr-1 inline h-3.5 w-3.5" />}{day}</button>)}</div>}</Section>
        <Section icon={Flame} title="Motivation & Gamification" subtitle="Customize your Study Streak experience."><ToggleRow label="Show XP" description="Display XP rewards after completing tasks." checked={settings.gamification.showXP} onChange={(value) => updateGroup('gamification', 'showXP', value)} /><ToggleRow label="Show Streaks" description="Display daily streak progress." checked={settings.gamification.showStreak} onChange={(value) => updateGroup('gamification', 'showStreak', value)} /><ToggleRow label="Achievement Animations" description="Show short animations when achievements are unlocked." checked={settings.gamification.achievementAnimations} onChange={(value) => updateGroup('gamification', 'achievementAnimations', value)} /><ToggleRow label="Completion Animations" description="Show the lightning animation when tasks are completed." checked={settings.gamification.completionAnimations} onChange={(value) => updateGroup('gamification', 'completionAnimations', value)} /></Section>
        <Section icon={UserRound} title="Account" subtitle="Your authenticated account details."><div className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-slate-500">Profile Name</p><p className="font-semibold text-slate-900 dark:text-slate-100">{user?.name || 'Learner'}</p></div><div><p className="text-xs text-slate-500">Email</p><p className="break-all font-semibold text-slate-900 dark:text-slate-100">{user?.email || 'Not available'}</p></div><div><p className="text-xs text-slate-500">Role</p><p className="font-semibold capitalize text-slate-900 dark:text-slate-100">{user?.role || 'student'}</p></div></div><button type="button" onClick={() => navigate('/profile')} className="rounded-xl border border-orange-200 px-4 py-2 text-sm font-semibold text-orange-700 hover:bg-orange-50 dark:border-orange-500/30 dark:text-orange-300 dark:hover:bg-orange-500/10">Edit Profile</button></Section>
        <Section icon={LockKeyhole} title="Security" subtitle="Manage account access without exposing sensitive credentials."><SecuritySettings /></Section>
        <Section icon={Shield} title="Data & Privacy" subtitle="Control your stored study data and account lifecycle."><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-semibold text-slate-800 dark:text-slate-200">Export My Study Data</p><p className="text-sm text-slate-600 dark:text-slate-400">Data export is not available yet.</p></div><button type="button" disabled className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-400 dark:border-slate-700">Unavailable</button></div><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-semibold text-slate-800 dark:text-slate-200">Delete Completed Plans</p><p className="text-sm text-slate-600 dark:text-slate-400">Manage completed plans from My Plans.</p></div><button type="button" onClick={() => navigate('/plans')} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700 dark:border-slate-700 dark:text-slate-300">Manage Completed Plans</button></div><div className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-red-200 bg-red-50/60 p-4 dark:border-red-500/30 dark:bg-red-500/10"><div><p className="font-semibold text-red-700 dark:text-red-300">Delete Account</p><p className="text-sm text-red-600/80 dark:text-red-300/80">Account deletion is not available in the current API.</p></div><button type="button" onClick={() => setConfirmDelete(true)} className="rounded-xl border border-red-300 px-4 py-2 text-sm font-semibold text-red-600 dark:border-red-500/40 dark:text-red-400">Delete Account</button></div></Section>
        <div className="sticky bottom-4 flex justify-end gap-3 rounded-2xl border border-slate-200 bg-white/95 p-3 shadow-lg backdrop-blur dark:border-slate-800 dark:bg-slate-900/95"><button type="button" onClick={reset} className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 dark:border-slate-700 dark:text-slate-300">Reset to Defaults</button><button type="button" onClick={save} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-5 py-2.5 text-sm font-semibold text-white shadow-lg shadow-orange-500/20 hover:bg-orange-600 disabled:opacity-60"><Save className="h-4 w-4" />{saving ? 'Saving...' : 'Save Changes'}</button></div>
        <ConfirmModal isOpen={confirmDelete} title="Delete Account?" message="Are you sure you want to permanently delete your Study Streak Rescue account? Account deletion is not currently available." confirmLabel="Close" onConfirm={() => setConfirmDelete(false)} onCancel={() => setConfirmDelete(false)} />
    </div>;
};

export default SettingsPage;
